define({
    root: ({
        msg: {
            warning: { header: "Warning", message: "You are about to create a new Scheme, confirm to proceed" },
            newSchemeSelected: "You have selected a different GWS Scheme, do you want to proceed ?",
            assetNotInScheme: "This Asset does not belong to the current GWS Scheme",
            selectAScheme: "Please, select a Scheme first",
            newSchemeWithId: {
                start: "You are about to select a new Scheme, ",
                end: "Do you want to proceed ?"
            },
            clearSelection: "Any unsaved changes to the current feature will be lost. Do you want to proceed?",
            updateRegistration: "You are about to update the Scheme registration field, do you want to proceed ?",
            selfIntersectErrorUpdate: "Sorry, the polygon is self intersecting, please change it before editing",
            selfIntersectErrorCreate: "Sorry, the polygon is self intersecting, please change it before saving",
            placeholderInput: "Search for a scheme name",
            schemeNotFound: "Sorry, we can not find this Scheme."
        },
        ok: "Ok",
        cancel: "Cancel",
        _widgetLabel: "GWS Smart Editor",
        noEditPrivileges: "Your account does not have permission to create or modify data.",
        widgetActive: "Active",
        widgetNotActive: "Not Active",
        _featureAction_Edit: "Edit",
        title: "Select a template to create features",
        pressStr: "Press ",
        ctrlStr: " CTRL ",
        snapStr: " to enable snapping",
        close: "Close",
        featureLayers: "Feature Layers",
        searchTemplates: "Search Templates",
        noAvailableTempaltes: "No available templates",
        noCanCreateLayerAreCurrentlyVisible: "No creatable layers are currently visible.",
        relatedTables: "Related tables:",
        relatedRecords: "Related records:",
        noRelatedRecotds: "No related records found",
        editorCache: " - Editor Cache",
        presetFieldAlias: "Field",
        presetValue: "Preset Value",
        usePresetValues: " Use Preset Values (New features only)",
        editGeometry: " Edit Geometry",
        savePromptTitle: "Save feature",
        savePrompt: "Would you like to save the current feature?",
        deletePromptTitle: "Delete feature",
        deletePrompt: "Are you sure you want to delete the selected feature?",
        attachmentLoadingError: "Error uploading attachments",
        attachmentSaveDeleteWarning: "Warning: Changes to attachments are saved automatically",
        filterEditor: {
            all: "All",
            noAvailableTempaltes: "No available templates",
            searchTemplates: "Search Templates"
        },
        invalidConfiguration: "Widget is either not configured or the layers in the configuration are no longer in the map.  Please open the app in the builder mode and reconfigure the widget."
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hr": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nb": 1,
    "nl": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});